language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-19
    - sys-img-x86-android-29
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'